/**
 * Blind held-out fixtures for player-role-context-v1.
 */

import type { RoleHistoryGame } from '@/lib/context-center';

export type RoleHeldOutCase = {
  id: string;
  category: string;
  gameId: string;
  playerEntityId: string;
  teamId: string;
  season: string;
  targetGameStart: string;
  history: RoleHistoryGame[];
  expect: {
    seasonHistoryN: number;
    recentHistoryN: number;
    completeness: 'COMPLETE' | 'SOURCE_ONLY' | 'PARTIAL' | 'SOURCE_UNKNOWN';
    seasonMinutes: number | null;
    seasonFga: number | null;
    seasonFta: number | null;
    seasonAst: number | null;
    seasonTpa: number | null;
    recentMinutes: number | null;
    recentFga: number | null;
  };
};

function row(
  partial: Partial<RoleHistoryGame> & Pick<RoleHistoryGame, 'gameId' | 'gameStart' | 'teamId'>
): RoleHistoryGame {
  return {
    season: '2023',
    minutes: 30,
    points: 15,
    field_goals_attempted: 10,
    free_throws_attempted: 4,
    assists: 5,
    three_pointers_attempted: 4,
    three_pointers_made: 1,
    rebounds: 4,
    ...partial,
  };
}

const TIP = '2024-02-01T00:00:00Z';

export const ROLE_HELDOUT_CASES: RoleHeldOutCase[] = [
  {
    id: 'RH-cold',
    category: 'cold_start',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonMinutes: null,
      seasonFga: null,
      seasonFta: null,
      seasonAst: null,
      seasonTpa: null,
      recentMinutes: null,
      recentFga: null,
    },
  },
  {
    id: 'RH-n1',
    category: 'history_n_1',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [row({ gameId: '1', gameStart: '2024-01-10T00:00:00Z', teamId: '10', minutes: 28, field_goals_attempted: 12 })],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 28,
      seasonFga: 12,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 28,
      recentFga: 12,
    },
  },
  {
    id: 'RH-n2',
    category: 'history_n_2',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30, field_goals_attempted: 10, free_throws_attempted: 4, assists: 5, three_pointers_attempted: 4 }),
      row({ gameId: '2', gameStart: '2024-01-05T00:00:00Z', teamId: '10', minutes: 34, field_goals_attempted: 14, free_throws_attempted: 6, assists: 7, three_pointers_attempted: 8 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 32,
      seasonFga: 12,
      seasonFta: 5,
      seasonAst: 6,
      seasonTpa: 6,
      recentMinutes: 32,
      recentFga: 12,
    },
  },
  {
    id: 'RH-gt10',
    category: 'history_n_gt10',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: Array.from({ length: 12 }, (_, i) =>
      row({
        gameId: `g${i + 1}`,
        gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
        teamId: '10',
        minutes: i + 1,
        field_goals_attempted: i + 1,
      })
    ),
    expect: {
      seasonHistoryN: 12,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonMinutes: 6.5,
      seasonFga: 6.5,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 7.5,
      recentFga: 7.5,
    },
  },
  {
    id: 'RH-rollover',
    category: 'recent_rollover',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: 'early', gameStart: '2023-12-15T00:00:00Z', teamId: '10', minutes: 100 }),
      ...Array.from({ length: 12 }, (_, i) =>
        row({
          gameId: `g${i + 1}`,
          gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
          teamId: '10',
          minutes: i + 1,
        })
      ),
    ],
    expect: {
      seasonHistoryN: 13,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonMinutes: (100 + 78) / 13,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 7.5,
      recentFga: 10,
    },
  },
  {
    id: 'RH-season-reset',
    category: 'season_reset',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [row({ gameId: 'old', gameStart: '2023-01-01T00:00:00Z', teamId: '10', season: '2022', minutes: 40 })],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonMinutes: null,
      seasonFga: null,
      seasonFta: null,
      seasonAst: null,
      seasonTpa: null,
      recentMinutes: null,
      recentFga: null,
    },
  },
  {
    id: 'RH-trade',
    category: 'trade_reset',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: 'B',
    season: '2023',
    targetGameStart: TIP,
    history: [row({ gameId: 'a1', gameStart: '2024-01-01T00:00:00Z', teamId: 'A', minutes: 40 })],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonMinutes: null,
      seasonFga: null,
      seasonFta: null,
      seasonAst: null,
      seasonTpa: null,
      recentMinutes: null,
      recentFga: null,
    },
  },
  {
    id: 'RH-return',
    category: 'return_stint',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: 'A',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: 'a1', gameStart: '2024-01-01T00:00:00Z', teamId: 'A', minutes: 30 }),
      row({ gameId: 'a2', gameStart: '2024-01-05T00:00:00Z', teamId: 'A', minutes: 34 }),
      row({ gameId: 'b1', gameStart: '2024-01-10T00:00:00Z', teamId: 'B', minutes: 20 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 32,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 32,
      recentFga: 10,
    },
  },
  {
    id: 'RH-dnp',
    category: 'dnp_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30 }),
      row({
        gameId: 'dnp',
        gameStart: '2024-01-03T00:00:00Z',
        teamId: '10',
        minutes: '00',
        points: 0,
        field_goals_attempted: 0,
        free_throws_attempted: 0,
        assists: 0,
        three_pointers_attempted: 0,
        three_pointers_made: 0,
        rebounds: 0,
      }),
      row({ gameId: '2', gameStart: '2024-01-05T00:00:00Z', teamId: '10', minutes: 34 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 32,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 32,
      recentFga: 10,
    },
  },
  {
    id: 'RH-same-tip',
    category: 'same_tip_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30 }),
      row({ gameId: 'same', gameStart: TIP, teamId: '10', minutes: 48, field_goals_attempted: 40 }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 30,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 30,
      recentFga: 10,
    },
  },
  {
    id: 'RH-future',
    category: 'future_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30 }),
      row({ gameId: 'fut', gameStart: '2024-02-10T00:00:00Z', teamId: '10', minutes: 48 }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 30,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 30,
      recentFga: 10,
    },
  },
  {
    id: 'RH-target-outcome',
    category: 'target_outcome_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30, field_goals_attempted: 10 }),
      row({ gameId: '2', gameStart: '2024-01-05T00:00:00Z', teamId: '10', minutes: 34, field_goals_attempted: 14 }),
      row({ gameId: 'T', gameStart: TIP, teamId: '10', minutes: 48, field_goals_attempted: 40 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 32,
      seasonFga: 12,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 32,
      recentFga: 12,
    },
  },
  {
    id: 'RH-ot',
    category: 'overtime_minutes',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [row({ gameId: 'ot', gameStart: '2024-01-10T00:00:00Z', teamId: '10', minutes: 53 })],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 53,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 53,
      recentFga: 10,
    },
  },
  {
    id: 'RH-exact',
    category: 'metric_exact_means',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30, field_goals_attempted: 10, free_throws_attempted: 4, assists: 5, three_pointers_attempted: 4 }),
      row({ gameId: '2', gameStart: '2024-01-05T00:00:00Z', teamId: '10', minutes: 34, field_goals_attempted: 14, free_throws_attempted: 6, assists: 7, three_pointers_attempted: 8 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 32,
      seasonFga: 12,
      seasonFta: 5,
      seasonAst: 6,
      seasonTpa: 6,
      recentMinutes: 32,
      recentFga: 12,
    },
  },
  {
    id: 'RH-ingest-prep',
    category: 'next_game_ingestion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 30 })],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 30,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 30,
      recentFga: 10,
    },
  },
  {
    id: 'RH-recent-lt10',
    category: 'recent_n_lt10',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: Array.from({ length: 4 }, (_, i) =>
      row({
        gameId: `g${i}`,
        gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
        teamId: '10',
        minutes: 20 + i,
      })
    ),
    expect: {
      seasonHistoryN: 4,
      recentHistoryN: 4,
      completeness: 'COMPLETE',
      seasonMinutes: 21.5,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 21.5,
      recentFga: 10,
    },
  },
  {
    id: 'RH-delta-large',
    category: 'large_recent_vs_season',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      ...Array.from({ length: 10 }, (_, i) =>
        row({
          gameId: `early${i}`,
          gameStart: `2023-11-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
          teamId: '10',
          minutes: 10,
        })
      ),
      ...Array.from({ length: 10 }, (_, i) =>
        row({
          gameId: `late${i}`,
          gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
          teamId: '10',
          minutes: 36,
        })
      ),
    ],
    expect: {
      seasonHistoryN: 20,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonMinutes: 23,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 36,
      recentFga: 10,
    },
  },
  {
    id: 'RH-recent10',
    category: 'recent_n_10',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: Array.from({ length: 10 }, (_, i) =>
      row({
        gameId: `g${i}`,
        gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
        teamId: '10',
        minutes: 24,
      })
    ),
    expect: {
      seasonHistoryN: 10,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonMinutes: 24,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 24,
      recentFga: 10,
    },
  },
  {
    id: 'RH-parity',
    category: 'role_expectation_parity',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', minutes: 20, field_goals_attempted: 8, points: 10 }),
      row({ gameId: '2', gameStart: '2024-01-05T00:00:00Z', teamId: '10', minutes: 40, field_goals_attempted: 22, points: 30 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonMinutes: 30,
      seasonFga: 15,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 30,
      recentFga: 15,
    },
  },
  {
    id: 'RH-future2',
    category: 'future_exclusion_extra',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-20T00:00:00Z', teamId: '10', minutes: 22 }),
      row({ gameId: '2', gameStart: '2024-03-01T00:00:00Z', teamId: '10', minutes: 40 }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonMinutes: 22,
      seasonFga: 10,
      seasonFta: 4,
      seasonAst: 5,
      seasonTpa: 4,
      recentMinutes: 22,
      recentFga: 10,
    },
  },
];
