/**
 * Blind held-out fixtures for recent-form-context-v1.
 * Freeze SHA before final certification run.
 */

import type { RoleHistoryGame } from '@/lib/context-center';

export type FormHeldOutCase = {
  id: string;
  category: string;
  gameId: string;
  playerEntityId: string;
  teamId: string;
  season: string;
  targetGameStart: string;
  history: RoleHistoryGame[];
  expect: {
    seasonHistoryN: number;
    recentHistoryN: number;
    completeness: 'COMPLETE' | 'SOURCE_ONLY' | 'PARTIAL' | 'SOURCE_UNKNOWN';
    seasonPoints: number | null;
    seasonRebounds: number | null;
    seasonTpm: number | null;
    seasonFgPct: number | null;
    seasonThreePct: number | null;
    recentPoints: number | null;
    recentFgPct: number | null;
    recentThreePct: number | null;
  };
};

function row(
  partial: Partial<RoleHistoryGame> & Pick<RoleHistoryGame, 'gameId' | 'gameStart' | 'teamId'>
): RoleHistoryGame {
  return {
    season: '2023',
    minutes: 30,
    points: 20,
    rebounds: 5,
    assists: 4,
    field_goals_made: 8,
    field_goals_attempted: 16,
    three_pointers_made: 2,
    three_pointers_attempted: 6,
    free_throws_attempted: 4,
    ...partial,
  };
}

const TIP = '2024-02-01T00:00:00Z';

export const FORM_HELDOUT_CASES: FormHeldOutCase[] = [
  {
    id: 'FH-cold',
    category: 'cold_start',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonPoints: null,
      seasonRebounds: null,
      seasonTpm: null,
      seasonFgPct: null,
      seasonThreePct: null,
      recentPoints: null,
      recentFgPct: null,
      recentThreePct: null,
    },
  },
  {
    id: 'FH-n1',
    category: 'history_n_1',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        points: 28,
        rebounds: 7,
        three_pointers_made: 4,
        field_goals_made: 10,
        field_goals_attempted: 20,
        three_pointers_attempted: 10,
      }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonPoints: 28,
      seasonRebounds: 7,
      seasonTpm: 4,
      seasonFgPct: 0.5,
      seasonThreePct: 0.4,
      recentPoints: 28,
      recentFgPct: 0.5,
      recentThreePct: 0.4,
    },
  },
  {
    id: 'FH-rollover',
    category: 'recent_rollover',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: '2024-01-20T00:00:00Z',
    history: Array.from({ length: 12 }, (_, i) => {
      const n = i + 1;
      return row({
        gameId: `g${n}`,
        gameStart: `2024-01-${String(n).padStart(2, '0')}T00:00:00Z`,
        teamId: '10',
        points: n,
        rebounds: 1,
        three_pointers_made: 1,
        field_goals_made: n,
        field_goals_attempted: 10,
        three_pointers_attempted: 2,
      });
    }),
    expect: {
      seasonHistoryN: 12,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonPoints: 6.5,
      seasonRebounds: 1,
      seasonTpm: 1,
      seasonFgPct: 78 / 120,
      seasonThreePct: 12 / 24,
      recentPoints: 7.5,
      recentFgPct: 75 / 100,
      recentThreePct: 10 / 20,
    },
  },
  {
    id: 'FH-trade',
    category: 'trade_reset',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: 'B',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: 'a1', gameStart: '2024-01-01T00:00:00Z', teamId: 'A', points: 30 }),
      row({ gameId: 'a2', gameStart: '2024-01-10T00:00:00Z', teamId: 'A', points: 30 }),
    ],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonPoints: null,
      seasonRebounds: null,
      seasonTpm: null,
      seasonFgPct: null,
      seasonThreePct: null,
      recentPoints: null,
      recentFgPct: null,
      recentThreePct: null,
    },
  },
  {
    id: 'FH-return',
    category: 'return_A_B_A',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: 'A',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: 'a1', gameStart: '2024-01-01T00:00:00Z', teamId: 'A', points: 20, rebounds: 4 }),
      row({ gameId: 'a2', gameStart: '2024-01-05T00:00:00Z', teamId: 'A', points: 30, rebounds: 8 }),
      row({ gameId: 'b1', gameStart: '2024-01-10T00:00:00Z', teamId: 'B', points: 40, rebounds: 12 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 25,
      seasonRebounds: 6,
      seasonTpm: 2,
      seasonFgPct: 16 / 32,
      seasonThreePct: 4 / 12,
      recentPoints: 25,
      recentFgPct: 16 / 32,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-season-reset',
    category: 'season_reset',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: 'old',
        gameStart: '2023-01-01T00:00:00Z',
        teamId: '10',
        season: '2022',
        points: 40,
      }),
    ],
    expect: {
      seasonHistoryN: 0,
      recentHistoryN: 0,
      completeness: 'SOURCE_ONLY',
      seasonPoints: null,
      seasonRebounds: null,
      seasonTpm: null,
      seasonFgPct: null,
      seasonThreePct: null,
      recentPoints: null,
      recentFgPct: null,
      recentThreePct: null,
    },
  },
  {
    id: 'FH-dnp',
    category: 'dnp_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', points: 20 }),
      row({
        gameId: 'dnp',
        gameStart: '2024-01-05T00:00:00Z',
        teamId: '10',
        minutes: '00',
        points: 0,
        rebounds: 0,
        field_goals_made: 0,
        field_goals_attempted: 0,
        three_pointers_made: 0,
        three_pointers_attempted: 0,
      }),
      row({ gameId: '2', gameStart: '2024-01-10T00:00:00Z', teamId: '10', points: 30 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 25,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 16 / 32,
      seasonThreePct: 4 / 12,
      recentPoints: 25,
      recentFgPct: 16 / 32,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-same-tip',
    category: 'same_tip_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-10T00:00:00Z', teamId: '10', points: 22 }),
      row({
        gameId: 'same',
        gameStart: TIP,
        teamId: '10',
        points: 99,
        field_goals_made: 40,
        field_goals_attempted: 40,
      }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonPoints: 22,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 8 / 16,
      seasonThreePct: 2 / 6,
      recentPoints: 22,
      recentFgPct: 8 / 16,
      recentThreePct: 2 / 6,
    },
  },
  {
    id: 'FH-future',
    category: 'future_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-10T00:00:00Z', teamId: '10', points: 18 }),
      row({ gameId: 'fut', gameStart: '2024-03-01T00:00:00Z', teamId: '10', points: 50 }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonPoints: 18,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 8 / 16,
      seasonThreePct: 2 / 6,
      recentPoints: 18,
      recentFgPct: 8 / 16,
      recentThreePct: 2 / 6,
    },
  },
  {
    id: 'FH-target-exclude',
    category: 'target_outcome_exclusion',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        points: 15,
        field_goals_made: 6,
        field_goals_attempted: 12,
        three_pointers_made: 1,
        three_pointers_attempted: 4,
      }),
      row({
        gameId: 'T',
        gameStart: TIP,
        teamId: '10',
        points: 60,
        field_goals_made: 25,
        field_goals_attempted: 30,
        three_pointers_made: 10,
        three_pointers_attempted: 12,
      }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonPoints: 15,
      seasonRebounds: 5,
      seasonTpm: 1,
      seasonFgPct: 0.5,
      seasonThreePct: 0.25,
      recentPoints: 15,
      recentFgPct: 0.5,
      recentThreePct: 0.25,
    },
  },
  {
    id: 'FH-next-ingest',
    category: 'next_game_ingestion',
    gameId: 'NEXT',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: '2024-02-10T00:00:00Z',
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        points: 20,
        field_goals_made: 5,
        field_goals_attempted: 10,
      }),
      row({
        gameId: 'T',
        gameStart: TIP,
        teamId: '10',
        points: 40,
        field_goals_made: 15,
        field_goals_attempted: 20,
      }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 30,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 20 / 30,
      seasonThreePct: 4 / 12,
      recentPoints: 30,
      recentFgPct: 20 / 30,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-pooled-fg',
    category: 'pooled_fg_pct',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-01T00:00:00Z',
        teamId: '10',
        field_goals_made: 5,
        field_goals_attempted: 10,
      }),
      row({
        gameId: '2',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        field_goals_made: 9,
        field_goals_attempted: 20,
      }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 20,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 14 / 30,
      seasonThreePct: 4 / 12,
      recentPoints: 20,
      recentFgPct: 14 / 30,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-pooled-3p',
    category: 'pooled_three_pct',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-01T00:00:00Z',
        teamId: '10',
        three_pointers_made: 1,
        three_pointers_attempted: 2,
      }),
      row({
        gameId: '2',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        three_pointers_made: 3,
        three_pointers_attempted: 10,
      }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 20,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 16 / 32,
      seasonThreePct: 4 / 12,
      recentPoints: 20,
      recentFgPct: 16 / 32,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-zero-3pa',
    category: 'zero_attempt_three_pct_partial',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-01T00:00:00Z',
        teamId: '10',
        points: 12,
        rebounds: 8,
        three_pointers_made: 0,
        three_pointers_attempted: 0,
        field_goals_made: 6,
        field_goals_attempted: 12,
      }),
      row({
        gameId: '2',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        points: 16,
        rebounds: 10,
        three_pointers_made: 0,
        three_pointers_attempted: 0,
        field_goals_made: 8,
        field_goals_attempted: 14,
      }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'PARTIAL',
      seasonPoints: 14,
      seasonRebounds: 9,
      seasonTpm: 0,
      seasonFgPct: 14 / 26,
      seasonThreePct: null,
      recentPoints: 14,
      recentFgPct: 14 / 26,
      recentThreePct: null,
    },
  },
  {
    id: 'FH-gt10',
    category: 'history_n_gt_10',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: '2024-01-25T00:00:00Z',
    history: Array.from({ length: 15 }, (_, i) => {
      const n = i + 1;
      return row({
        gameId: `h${n}`,
        gameStart: `2024-01-${String(n).padStart(2, '0')}T00:00:00Z`,
        teamId: '10',
        points: 10,
        rebounds: 2,
        three_pointers_made: 1,
        field_goals_made: 4,
        field_goals_attempted: 10,
        three_pointers_attempted: 3,
      });
    }),
    expect: {
      seasonHistoryN: 15,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      seasonPoints: 10,
      seasonRebounds: 2,
      seasonTpm: 1,
      seasonFgPct: 60 / 150,
      seasonThreePct: 15 / 45,
      recentPoints: 10,
      recentFgPct: 40 / 100,
      recentThreePct: 10 / 30,
    },
  },
  {
    id: 'FH-count-exact',
    category: 'counting_stat_exact',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-01T00:00:00Z',
        teamId: '10',
        points: 20,
        rebounds: 5,
        three_pointers_made: 2,
      }),
      row({
        gameId: '2',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        points: 30,
        rebounds: 7,
        three_pointers_made: 4,
      }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 25,
      seasonRebounds: 6,
      seasonTpm: 3,
      seasonFgPct: 16 / 32,
      seasonThreePct: 6 / 12,
      recentPoints: 25,
      recentFgPct: 16 / 32,
      recentThreePct: 6 / 12,
    },
  },
  {
    id: 'FH-large-delta',
    category: 'large_recent_vs_season',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: '2024-01-25T00:00:00Z',
    history: [
      ...Array.from({ length: 10 }, (_, i) =>
        row({
          gameId: `early${i}`,
          gameStart: `2024-01-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
          teamId: '10',
          points: 10,
          rebounds: 2,
          three_pointers_made: 0,
          field_goals_made: 4,
          field_goals_attempted: 12,
          three_pointers_attempted: 2,
        })
      ),
      ...Array.from({ length: 5 }, (_, i) =>
        row({
          gameId: `hot${i}`,
          gameStart: `2024-01-${String(i + 15).padStart(2, '0')}T00:00:00Z`,
          teamId: '10',
          points: 30,
          rebounds: 8,
          three_pointers_made: 4,
          field_goals_made: 12,
          field_goals_attempted: 20,
          three_pointers_attempted: 8,
        })
      ),
    ],
    expect: {
      seasonHistoryN: 15,
      recentHistoryN: 10,
      completeness: 'COMPLETE',
      // season: 10*10 + 5*30 = 250 / 15
      seasonPoints: 250 / 15,
      seasonRebounds: (10 * 2 + 5 * 8) / 15,
      seasonTpm: (10 * 0 + 5 * 4) / 15,
      seasonFgPct: (10 * 4 + 5 * 12) / (10 * 12 + 5 * 20),
      seasonThreePct: (10 * 0 + 5 * 4) / (10 * 2 + 5 * 8),
      // recent last 10 = 5 early(10) + 5 hot(30) → wait: early is 1-10, hot is 15-19
      // last 10 by time: early6-10 (5 games) + hot0-4 (5) = points (5*10+5*30)/10 = 20
      recentPoints: 20,
      recentFgPct: (5 * 4 + 5 * 12) / (5 * 12 + 5 * 20),
      recentThreePct: (5 * 0 + 5 * 4) / (5 * 2 + 5 * 8),
    },
  },
  {
    id: 'FH-parity',
    category: 'role_form_history_parity',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: '1', gameStart: '2024-01-01T00:00:00Z', teamId: '10', points: 12 }),
      row({
        gameId: 'dnp',
        gameStart: '2024-01-05T00:00:00Z',
        teamId: '10',
        minutes: '00',
        points: 0,
      }),
      row({ gameId: '2', gameStart: '2024-01-12T00:00:00Z', teamId: '10', points: 18 }),
    ],
    expect: {
      seasonHistoryN: 2,
      recentHistoryN: 2,
      completeness: 'COMPLETE',
      seasonPoints: 15,
      seasonRebounds: 5,
      seasonTpm: 2,
      seasonFgPct: 16 / 32,
      seasonThreePct: 4 / 12,
      recentPoints: 15,
      recentFgPct: 16 / 32,
      recentThreePct: 4 / 12,
    },
  },
  {
    id: 'FH-zero-fga-partial',
    category: 'zero_fga_partial',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: '10',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({
        gameId: '1',
        gameStart: '2024-01-10T00:00:00Z',
        teamId: '10',
        minutes: 1,
        points: 0,
        rebounds: 1,
        three_pointers_made: 0,
        three_pointers_attempted: 0,
        field_goals_made: 0,
        field_goals_attempted: 0,
      }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'PARTIAL',
      seasonPoints: 0,
      seasonRebounds: 1,
      seasonTpm: 0,
      seasonFgPct: null,
      seasonThreePct: null,
      recentPoints: 0,
      recentFgPct: null,
      recentThreePct: null,
    },
  },
  {
    id: 'FH-trade-then-b',
    category: 'trade_then_team_b_history',
    gameId: 'T',
    playerEntityId: 'P',
    teamId: 'B',
    season: '2023',
    targetGameStart: TIP,
    history: [
      row({ gameId: 'a1', gameStart: '2024-01-01T00:00:00Z', teamId: 'A', points: 30 }),
      row({
        gameId: 'b1',
        gameStart: '2024-01-15T00:00:00Z',
        teamId: 'B',
        points: 14,
        rebounds: 3,
        three_pointers_made: 1,
        field_goals_made: 5,
        field_goals_attempted: 11,
        three_pointers_attempted: 4,
      }),
    ],
    expect: {
      seasonHistoryN: 1,
      recentHistoryN: 1,
      completeness: 'COMPLETE',
      seasonPoints: 14,
      seasonRebounds: 3,
      seasonTpm: 1,
      seasonFgPct: 5 / 11,
      seasonThreePct: 1 / 4,
      recentPoints: 14,
      recentFgPct: 5 / 11,
      recentThreePct: 1 / 4,
    },
  },
];
